travelguide/config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :tours
  resources :flights
  resources :resaturants
  resources :guesthouses
  resources :hotels
  resources :places
  root "places#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

travelguide/app/models/tour.rb
class Tour < ApplicationRecord
end

travelguide/app/controllers/tours_controller.rb
class ToursController < ApplicationController
  http_basic_authenticate_with name: "Tour", password: "hero1234", except: [:index, :show]
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name, :location, :contact, :email)
    end
end

travelguide/app/helpers/tours_helper.rb
module ToursHelper
end

travelguide/app/views/tours/_form.html.erb
<%= form_for @tour, :html => { :class => "form-horizontal tour" } do |f| %>

  <% if @tour.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tours_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

travelguide/app/views/tours/edit.html.erb
<%- model_class = Tour -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

travelguide/app/views/tours/index.html.erb
<%- model_class = Tour -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= link_to tour.id, tour_path(tour) %></td>
        <td><%= tour.name %></td>
        <td><%= tour.location %></td>
        <td><%= tour.contact %></td>
        <td><%= tour.email %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      tour_path(tour), :class => 'btn btn-default btn-xs' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tour_path,
            :class => 'btn btn-primary' %>

travelguide/app/views/tours/new.html.erb
<%- model_class = Tour -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

travelguide/app/views/tours/show.html.erb
<%- model_class = Tour -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @tour.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @tour.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @tour.contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @tour.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tours_path, :class => 'btn btn-default'  %>